executor: slurm
default-resources:
  slurm_account: 'goldman'
  mem: 5GB
  cpus_per_task: 1
  runtime: 50

printshellcmds: True

sdm:
  - conda


set-threads:
  map_paf: 4
  map_sam: 4
  pileup: 4

retries: 2

latency-wait: 60

jobs: 100

groups:
  - record_unblocks=UNBLOCK
  - separate_target=SEPARATE

group-components:
  - UNBLOCK=100
  - SEPARATE=10

