executor: slurm
default-resources:
  slurm_account: 'goldman'
  mem: 15GB
  cpus_per_task: 4
  runtime: 50

printshellcmds: True

sdm:
  - conda


set-threads:
  map_paf: 4
  map_sam: 4
  pileup: 4


groups:
  - record_unblocks=UNBLOCK
  - separate_target=SEPARATE

group-components:
  - UNBLOCK=100
  - SEPARATE=10

