
exp_name: 'debug_spikes3'
ref: '/nfs/research/goldman/ipoetzsch/trio_exp2/GCA_009914755-chromosome-21.fasta'
reads: '/hps/nobackup/goldman/ipoetzsch/debug_sim_chr21/'
conditions:
  - 'boss'
  - 'control'
max_timepoint: 16
mu: 400
dump_time: 35_000_000
pores: 512
log_time_stamp: '20250411-150100'
