
exp_name: 'save_masks_sim_chr21_second_correction'
ref: '/nfs/research/goldman/ipoetzsch/trio_exp2/GCA_009914755-chromosome-21.fasta'
reads: '/hps/nobackup/goldman/ipoetzsch/'
conditions:
  - 'boss'
  - 'control'
max_timepoint: 10
mu: 400
dump_time: 35_000_000
pores: 512
log_time_stamp: '20250619-114626'
